### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by delmendo** [louischatriot/trello-capture#11]
I just put in some issues.   It seems to work fine under Linux - but my co-workers all run Windows 8.  

I'd really like this extension to work since I need it at work :) I'm happy to work on it, but before I go thru that I wanted to find out:If I put in a pull request with fixes - will you accept it  and push out changes to the Chrome store? 

or is this a dead project for you?

**Comment by louischatriot** [comment]
The project is not dead but I absolutely don't have the time to take care of making it work with windows. If you can do it I'll happily review your PR and deploy new changes, thanks !

**Comment by delmendo** [comment]
awesome! The fixes are small - I'll test tonight and submit a PR

**Comment by delmendo** [comment]
Ok I put in two pull requests - 1 with all the bug fixes and the other one with a small feature tweak.  Let me know if I need to do anything else.

**Comment by delmendo** [comment]
1. Thanks for the roll out - it fixed it up for my co-workers :)
2. Are you open to taking feature pull requests? or are you just in maintenance mode?

**Comment by louischatriot** [comment]
Am I open to PRs but I have very limited time so I prioritize heavily bugfixes.
